default: &default
  adapter: postgresql
  username: postgres
  password: sdm2016
  pool: 5
  timeout: 5000
#  port: 5432
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>
#  database: strano_<%= Rails.env %>
#  min_messages: ERROR

development:
  <<: *default
  database: serler_stream2_dev

test:
  <<: *default
  database: serler_stream2_test

production:
  <<: *default
  database: serler_stream2_pro

cucumber:
  <<: *test
